# Server port
server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true

#Spring
spring:
  config:
    import: application-secret.yml
  datasource:
    url: jdbc:mariadb://localhost:3306/book_everywhere
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      properties: # Additional native properties to set on the JPA provider.
        hibernate:
          #show-sql: true                  # System.out 으로 출력
          format_sql: true                 # 로그, 콘솔의 SQL을 좀 더 이쁘게 출력합니다.
          #highlight_sql: true             # SQL 출력을 ANSI escape codes를 사용하여 색을 부여합니다.
          #use_sql_comments: true          # 보다 쉬운 디버깅을 위해 SQL 내부에 /* */의 주석을 추가합니다.


# Logging
logging:
  level: # 각 package 별로 로깅 레벨을 지정할 수 있다.
   rg.hibernate.type: trace  # 콘솔차에 조건에 바인딩되는 값 및 조회 결과 출력

file:
  path: C:/workspace/bookeverywhere/upload/